### ISSUE TITLE
Opaque oids not importing

### ISSUE THREAD

**Issue by ianrapid** [patrickscottbest/OIDrage#2]
Hi, I noticed that floats don't seem to be importing (at least for me).

**Comment by patrickscottbest** [comment]
Thanks for the bug report - I replicated it.

I didn't even need to turn on DEBUG - i see it in the logging at load time.  Maybe this should be a [WARN] .

`2022-12-22 09:43:37,665 [MainThread  ] [INFO ]  Problem:  while importing this line: .1.3.6.1.4.1.2021.10.1.6.3 = Opaque: Float: 0.062500`
